server:
  port: 8080

spring:
  application:
    name: xblog-api
  datasource:
    url: jdbc:mysql://localhost:3306/xblog?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    tomcat:
      init-s-q-l: SET NAMES utf8mb4

mybatis-plus:
  mapper-locations: classpath:mapper/*Mapper.xml